<a href="https://colab.research.google.com/github/gbaser54/data-science-assignments/blob/master/data_science_assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import numpy as np

In [3]:
import numpy as np

Make a python list => [1,2,3,4,5]

Convert it into numpy array and print it

In [7]:
list=[1,2,3,4,5]
ne=np.array(list)

Make a python matrix (3 x 3) => [[1,2,3],[4,5,6],[7,8,9]]

Convert it into numpy array and print it

In [6]:
lis=[[1,2,3],[4,5,6],[7,8,9]]
arr1=np.array(lis)
arr1.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Make a matrix (3 x 3) using built-in methods (like arange(), reshape() etc.):

[ [1,3,5],

[7,9,11],

[13,15,17] ]

In [ ]:
li=np.arange(1,18,2).reshape(3,3)
print(li)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


Create a numpy array with 10 random numbers from 0 to 10 (there should be few numbers greater than 1)

In [11]:
arr2=np.random.randint(0,10,10)
arr2

array([5, 5, 8, 4, 9, 8, 1, 1, 0, 6])

Create numpy array => [1,2,3,4,5] and convert it to 2D array with 5 rows

In [12]:
list2=[1,2,3,4,5]
arr3=np.array(list2)
arr3.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])


Print the shape of the above created array

In [17]:
arr4=arr3.reshape(5,1)
arr4.shape

(5, 1)

Create a numpy array with 10 elements in it. Access and print its 3rd, 4th and 9th element.

In [29]:
list4=[1,2,3,4,5,6,7,8,9,10]
ranrr2=np.array(list4)
ranrr2[2]
ranrr2[3]
ranrr2[8]


9

Print alternate elements of that array

In [33]:
i=0
while i<ranrr2.size:
  print(ranrr2[i])
  i=i+2


1
3
5
7
9



Change last 3 elements into 100 using broadcasting and print

In [38]:
ranrr2[7:10]=100
ranrr2

array([  1,   2,   3,   4,   5,   6,   7, 100, 100, 100])

Create a 5 x 5 matrix (fill it with any element you like), print it.

Then print the middle (3 x 3) matrix.

In [56]:
ranrr3=np.arange(25)
ranrr3.reshape(5,5)
ranrr4=ranrr3.reshape(5,5)
ranrr4[1:4, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])